import type { CSSProperties } from "react";
import type { DiffLineKind } from "./helpers";

/** Co-located styles for EvalCaseModal. */
export const s = {
  body: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 0, minHeight: 360 } satisfies CSSProperties,
  col: { padding: 24, display: "flex", flexDirection: "column", gap: 14, minWidth: 0 } satisfies CSSProperties,
  colRight: { padding: 24, display: "flex", flexDirection: "column", gap: 14, minWidth: 0, borderLeft: "1px solid var(--border)" } satisfies CSSProperties,
  label: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  labelRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  editor: {
    width: "100%",
    minHeight: 260,
    flex: 1,
    resize: "vertical",
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    fontSize: 12.5,
    lineHeight: 1.55,
  } satisfies CSSProperties,
  diff: {
    margin: 0,
    padding: "10px 0",
    flex: 1,
    minHeight: 260,
    overflow: "auto",
    border: "1px solid var(--border)",
    borderRadius: 7,
    background: "var(--bg-surface)",
    fontSize: 12.5,
    lineHeight: 1.6,
  } satisfies CSSProperties,
  diffLine: (kind: DiffLineKind): CSSProperties => ({
    padding: "0 12px",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    color: kind === "hunk" ? "var(--accent-text)" : kind === "ctx" ? "var(--text-secondary)" : "var(--text-primary)",
    background: kind === "add" ? "var(--ok-bg)" : kind === "del" ? "var(--crit-bg)" : "transparent",
  }),
  validity: (ok: boolean): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    fontWeight: 600,
    padding: "2px 9px",
    borderRadius: 5,
    color: ok ? "var(--ok)" : "var(--crit)",
    background: ok ? "var(--ok-bg)" : "var(--crit-bg)",
  }),
  result: (pass: boolean | null): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 7,
    fontSize: 13,
    color: "var(--text-secondary)",
    border: "1px solid " + (pass === null ? "var(--border)" : pass ? "var(--ok)" : "var(--crit)"),
    background: pass === null ? "transparent" : pass ? "var(--ok-bg)" : "var(--crit-bg)",
  }),
  resultStrong: { fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
  footer: { display: "flex", justifyContent: "flex-end", gap: 8 } satisfies CSSProperties,
} as const;
