-- Generated by drizzle-kit, then made idempotent: the shared dev volume
-- (devdigest_pgdata) already carries these objects from a reverted branch, and a
-- plain ADD COLUMN / ADD CONSTRAINT would fail there with 42701 / 42710.
ALTER TABLE "agent_skills" ADD COLUMN IF NOT EXISTS "enabled" boolean DEFAULT true NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "skills_workspace_idx" ON "skills" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agent_skills_skill_idx" ON "agent_skills" USING btree ("skill_id");--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'skills_type_ck') THEN
    ALTER TABLE "skills" ADD CONSTRAINT "skills_type_ck" CHECK ("skills"."type" in ('rubric', 'convention', 'security', 'custom'));
  END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'skills_source_ck') THEN
    ALTER TABLE "skills" ADD CONSTRAINT "skills_source_ck" CHECK ("skills"."source" in ('manual', 'imported_url', 'extracted', 'community'));
  END IF;
END $$;
