-- Generated by drizzle-kit, then made idempotent: the shared dev volume
-- (devdigest_pgdata) already has most of these objects from a reverted branch.
ALTER TABLE "conventions" ADD COLUMN IF NOT EXISTS "category" text DEFAULT 'general' NOT NULL;--> statement-breakpoint
ALTER TABLE "conventions" ADD COLUMN IF NOT EXISTS "rationale" text;--> statement-breakpoint
ALTER TABLE "conventions" ADD COLUMN IF NOT EXISTS "evidence_line" integer;--> statement-breakpoint
ALTER TABLE "conventions" ADD COLUMN IF NOT EXISTS "pattern" text;--> statement-breakpoint
ALTER TABLE "conventions" ADD COLUMN IF NOT EXISTS "occurrences" integer;--> statement-breakpoint
ALTER TABLE "conventions" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'pending' NOT NULL;--> statement-breakpoint
ALTER TABLE "conventions" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conventions_repo_created_idx" ON "conventions" USING btree ("repo_id","created_at" DESC NULLS LAST);--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'conventions_category_ck') THEN
    ALTER TABLE "conventions" ADD CONSTRAINT "conventions_category_ck" CHECK ("conventions"."category" in ('naming', 'structure', 'errors', 'testing', 'imports', 'typing', 'api', 'general'));
  END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'conventions_status_ck') THEN
    ALTER TABLE "conventions" ADD CONSTRAINT "conventions_status_ck" CHECK ("conventions"."status" in ('pending', 'accepted', 'rejected'));
  END IF;
END $$;
