-- Generated by drizzle-kit, then made idempotent (the shared dev volume already dropped it).
-- A separate migration from 0013 so drizzle-kit never asks whether `accepted` was renamed.
ALTER TABLE "conventions" DROP COLUMN IF EXISTS "accepted";
