-- Generated by drizzle-kit, then made idempotent: the shared dev volume
-- (devdigest_pgdata) already carries columns from other worktrees' migrations,
-- so a plain ADD COLUMN can fail there with 42701.
ALTER TABLE "pr_intent" ADD COLUMN IF NOT EXISTS "derived_for_sha" text;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN IF NOT EXISTS "confidence" double precision;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN IF NOT EXISTS "sources" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN IF NOT EXISTS "missing_context" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN IF NOT EXISTS "provider" text;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN IF NOT EXISTS "model" text;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN IF NOT EXISTS "derived_at" timestamp with time zone;
