-- Generated by drizzle-kit, then made idempotent: the shared dev volume
-- (devdigest_pgdata) may already have this column dropped by another
-- worktree's migration run, so a plain DROP COLUMN can fail there.
ALTER TABLE "pr_intent" DROP COLUMN IF EXISTS "confidence";
