import type { CSSProperties } from "react";

/** Co-located styles for ProjectContextView (matches the Project Context mock). */
export const s = {
  frame: { display: "flex", height: "calc(100vh - 52px)" } satisfies CSSProperties,
  rail: {
    width: 232,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
    minHeight: 0,
  } satisfies CSSProperties,
  railHead: { padding: "16px 16px 8px" } satisfies CSSProperties,
  railTitle: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  railRoot: { fontSize: 12, color: "var(--text-secondary)", marginTop: 4, overflowWrap: "anywhere" } satisfies CSSProperties,
  toolbar: { display: "flex", gap: 4, padding: "4px 12px 10px" } satisfies CSSProperties,
  tree: { flex: 1, overflow: "auto", padding: "0 8px 12px" } satisfies CSSProperties,
  folder: { fontSize: 11, color: "var(--text-muted)", padding: "10px 8px 4px" } satisfies CSSProperties,
  list: { listStyle: "none", padding: 0, margin: 0 } satisfies CSSProperties,
  file: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "7px 10px",
    borderRadius: 6,
    border: "none",
    textAlign: "left",
    fontSize: 13,
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
    background: active ? "var(--bg-hover)" : "transparent",
  }),
  fileIcon: { color: "var(--accent)", flexShrink: 0 } satisfies CSSProperties,
  pane: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", minHeight: 0 } satisfies CSSProperties,
  paneHead: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "16px 28px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  paneName: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  paneMeta: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  paneBody: { flex: 1, overflow: "auto", padding: "24px 28px" } satisfies CSSProperties,
  message: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
