import type { CSSProperties } from "react";

/** Co-located styles for ProjectContextPicker (matches the agent / skill Context tab mocks). */
export const s = {
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 240,
  } satisfies CSSProperties,
  filterIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", marginBottom: 16 } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    maxWidth: 1000,
    listStyle: "none",
    padding: 0,
    margin: 0,
  } satisfies CSSProperties,
  row: (dragOver: boolean, attached: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid " + (dragOver ? "var(--accent)" : "var(--border)"),
    // Attached rows stand out, as in the mock; the rest sit back.
    background: attached ? "var(--bg-hover)" : "var(--bg-elevated)",
  }),
  handle: (enabled: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    cursor: enabled ? "grab" : "not-allowed",
    opacity: enabled ? 1 : 0.35,
    display: "inline-flex",
    background: "none",
    border: "none",
    padding: 0,
  }),
  name: { fontSize: 14, fontWeight: 500, color: "var(--text-primary)" } satisfies CSSProperties,
  folder: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  previewBtn: (iconOnly: boolean): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: iconOnly ? "5px 8px" : "5px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-secondary)",
    fontSize: 13,
  }),
  message: { fontSize: 13, color: "var(--text-muted)", padding: "12px 0" } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    maxWidth: 1000,
    marginTop: 20,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  tokens: { color: "var(--text-secondary)" } satisfies CSSProperties,
  footerNote: { marginLeft: "auto" } satisfies CSSProperties,
} as const;
