import type { CSSProperties } from "react";

/** Co-located styles for ConventionCard (matches the Conventions mock). */
export const s = {
  card: (accepted: boolean, rejected: boolean): CSSProperties => ({
    display: "flex",
    gap: 20,
    padding: "18px 20px 16px 22px",
    borderRadius: 10,
    border: "1px solid var(--border)",
    borderLeft: `3px solid ${accepted ? "var(--ok)" : "var(--border)"}`,
    background: "var(--bg-elevated)",
    opacity: rejected ? 0.55 : 1,
  }),
  main: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rule: {
    fontSize: 16,
    fontWeight: 600,
    fontStyle: "italic",
    marginBottom: 12,
    cursor: "text",
    background: "none",
    border: "none",
    padding: 0,
    color: "var(--text-primary)",
    textAlign: "left",
  } satisfies CSSProperties,
  ruleInput: {
    width: "100%",
    fontSize: 16,
    fontWeight: 600,
    fontStyle: "italic",
    marginBottom: 4,
    padding: "4px 8px",
    borderRadius: 6,
    border: "1px solid var(--accent)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    outline: "none",
  } satisfies CSSProperties,
  editHint: { fontSize: 11.5, color: "var(--text-muted)", marginBottom: 10 } satisfies CSSProperties,
  evidence: { border: "1px solid var(--border)", borderRadius: 8, background: "var(--bg-primary)", overflow: "hidden" } satisfies CSSProperties,
  evidenceHead: {
    display: "flex",
    alignItems: "center",
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  copy: { marginLeft: "auto", background: "none", border: "none", color: "var(--text-muted)", cursor: "pointer", display: "inline-flex" } satisfies CSSProperties,
  code: { margin: 0, padding: "12px 16px", fontSize: 13, lineHeight: 1.6, overflowX: "auto", whiteSpace: "pre" } satisfies CSSProperties,
  metaRow: { display: "flex", alignItems: "center", gap: 12, marginTop: 12, fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  bar: { width: 140 } satisfies CSSProperties,
  pct: { fontFamily: "var(--font-mono, ui-monospace, monospace)", color: "var(--text-secondary)" } satisfies CSSProperties,
  actions: { display: "flex", flexDirection: "column", gap: 10, width: 230, flexShrink: 0 } satisfies CSSProperties,
} as const;
