import type { CSSProperties } from "react";

/** Co-located styles for the Export-to-CI wizard and its steps. */
export const s = {
  stepper: { padding: "18px 24px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  body: { padding: 24, display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  card: (active: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "14px 16px",
    borderRadius: 8,
    textAlign: "left",
    width: "100%",
    color: "var(--text-primary)",
    background: active ? "var(--accent-bg)" : "var(--bg-surface)",
    border: "1px solid " + (active ? "var(--accent)" : "var(--border)"),
    cursor: "pointer",
  }),
  cardHead: { display: "flex", alignItems: "center", gap: 10, fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  cardBody: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  spacerInline: { marginLeft: "auto" } satisfies CSSProperties,
  label: { fontSize: 12, fontWeight: 600, letterSpacing: "0.06em", color: "var(--text-muted)", textTransform: "uppercase" } satisfies CSSProperties,
  row: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  warn: { fontSize: 13, color: "var(--warn)" } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--crit)", lineHeight: 1.5 } satisfies CSSProperties,
  note: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5, padding: "12px 14px", borderRadius: 8, border: "1px solid var(--border)", background: "var(--bg-surface)" } satisfies CSSProperties,
  files: { display: "grid", gridTemplateColumns: "240px 1fr", border: "1px solid var(--border)", borderRadius: 8, overflow: "hidden", minHeight: 280 } satisfies CSSProperties,
  fileList: { display: "flex", flexDirection: "column", padding: 8, gap: 2, borderRight: "1px solid var(--border)", background: "var(--bg-surface)" } satisfies CSSProperties,
  fileItem: (active: boolean): CSSProperties => ({
    textAlign: "left",
    padding: "8px 10px",
    borderRadius: 6,
    fontSize: 12.5,
    wordBreak: "break-all",
    color: active ? "var(--accent-text)" : "var(--text-secondary)",
    background: active ? "var(--accent-bg)" : "transparent",
  }),
  fileView: { display: "flex", flexDirection: "column", minWidth: 0 } satisfies CSSProperties,
  fileHead: { display: "flex", alignItems: "center", gap: 8, padding: "10px 14px", borderBottom: "1px solid var(--border)", fontSize: 12.5 } satisfies CSSProperties,
  fileText: { margin: 0, padding: 14, fontSize: 12.5, lineHeight: 1.55, overflow: "auto", whiteSpace: "pre", flex: 1, maxHeight: 360 } satisfies CSSProperties,
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13, border: "1px solid var(--border)" } satisfies CSSProperties,
  td: { padding: "10px 12px", borderBottom: "1px solid var(--border)", verticalAlign: "middle" } satisfies CSSProperties,
  radio: { display: "flex", alignItems: "center", gap: 8, fontSize: 14 } satisfies CSSProperties,
} as const;
